### ISSUE TITLE
Gmail Hack issue

### ISSUE THREAD

**Issue by MouroPixel** [mishakorzik/Gmail-Hack#6]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Gmail-Hack/Mail-Hack.py", line 58, in <module>
    smtp.login(user, password)
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 432, in docmd
    return self.getreply()
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by WinterWolf2-0** [comment]
Hey so im not 100% sure on this, but i think the google servers have a cooldown making this kinda useless
