### ISSUE TITLE
Проблема взлому 

### ISSUE THREAD

**Issue by Vov4ik13** [mishakorzik/Gmail-Hack#8]
Після вибрання почти жертви вибираю чисто 0 вибиває ось таке 
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Gmail-Hack/Mail-Hack.py", line 58, in <module>
    smtp.login(user, password)
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 432, in docmd
    return self.getreply()
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
Якщо можете допоможіть новачок в цій сфері.

**Comment by mishakorzik** [comment]
Це не проблема інструменту, скоріше всього у вас проблема з модулем smtplib.

**Comment by bsha4r** [comment]
https://github.com/mishakorzik/Gmail-Hack/issues/8#issue-1251583689
